/** Módulos de permiso (alineados al backend). */
export const PERMISSION_MODULES = {
  PATIENTS: "PATIENTS",
  PROCEDURES: "PROCEDURES",
  APPOINTMENTS: "APPOINTMENTS",
  USERS: "USERS",
  TREATMENTS: "TREATMENTS",
  PATIENT_TREATMENTS: "PATIENT_TREATMENTS",
  PAYMENTS: "PAYMENTS",
  CLINICAL_RECORDS: "CLINICAL_RECORDS",
} as const;

export type TPermissionModule =
  (typeof PERMISSION_MODULES)[keyof typeof PERMISSION_MODULES];

/** Códigos de permiso (alineados a PermissionCodes del backend). */
export const PERMISSION_CODES = {
  // Patients
  GET_PATIENTS: "GET_PATIENTS",
  CREATE_PATIENT: "CREATE_PATIENT",
  UPDATE_PATIENT: "UPDATE_PATIENT",
  DELETE_PATIENT: "DELETE_PATIENT",

  // Procedures
  GET_PROCEDURES: "GET_PROCEDURES",
  CREATE_PROCEDURE: "CREATE_PROCEDURE",
  UPDATE_PROCEDURE: "UPDATE_PROCEDURE",
  DELETE_PROCEDURE: "DELETE_PROCEDURE",

  // Appointments
  GET_APPOINTMENTS: "GET_APPOINTMENTS",
  CREATE_APPOINTMENT: "CREATE_APPOINTMENT",
  UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",

  // Users / Team
  GET_TEAM: "GET_TEAM",
  CREATE_MEMBER: "CREATE_MEMBER",

  // Treatments
  GET_TREATMENTS: "GET_TREATMENTS",
  CREATE_TREATMENT: "CREATE_TREATMENT",
  UPDATE_TREATMENT: "UPDATE_TREATMENT",
  DELETE_TREATMENT: "DELETE_TREATMENT",

  // Patient treatments
  CREATE_PATIENT_TREATMENT: "CREATE_PATIENT_TREATMENT",
  GET_PATIENT_TREATMENTS: "GET_PATIENT_TREATMENTS",
  UPDATE_PATIENT_TREATMENT: "UPDATE_PATIENT_TREATMENT",

  // Payments
  CREATE_PAYMENT: "CREATE_PAYMENT",
  GET_PAYMENTS: "GET_PAYMENTS",
  GET_PAYMENTS_SUMMARY_BY_CONCEPT: "GET_PAYMENTS_SUMMARY_BY_CONCEPT",

  // Clinical records
  CREATE_CLINICAL_RECORD: "CREATE_CLINICAL_RECORD",
  GET_CLINICAL_RECORDS: "GET_CLINICAL_RECORDS",
} as const;

export type TPermissionCode =
  (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

type TModuleCrudActions = {
  view?: TPermissionCode;
  create?: TPermissionCode;
  update?: TPermissionCode;
  delete?: TPermissionCode;
};

/**
 * Acciones básicas por módulo.
 * Si una acción no existe en el backend, se omite (can* → false).
 */
export const MODULE_CRUD = {
  [PERMISSION_MODULES.PATIENTS]: {
    view: PERMISSION_CODES.GET_PATIENTS,
    create: PERMISSION_CODES.CREATE_PATIENT,
    update: PERMISSION_CODES.UPDATE_PATIENT,
    delete: PERMISSION_CODES.DELETE_PATIENT,
  },
  [PERMISSION_MODULES.PROCEDURES]: {
    view: PERMISSION_CODES.GET_PROCEDURES,
    create: PERMISSION_CODES.CREATE_PROCEDURE,
    update: PERMISSION_CODES.UPDATE_PROCEDURE,
    delete: PERMISSION_CODES.DELETE_PROCEDURE,
  },
  [PERMISSION_MODULES.APPOINTMENTS]: {
    view: PERMISSION_CODES.GET_APPOINTMENTS,
    create: PERMISSION_CODES.CREATE_APPOINTMENT,
    update: PERMISSION_CODES.UPDATE_APPOINTMENT,
  },
  [PERMISSION_MODULES.USERS]: {
    view: PERMISSION_CODES.GET_TEAM,
    create: PERMISSION_CODES.CREATE_MEMBER,
  },
  [PERMISSION_MODULES.TREATMENTS]: {
    view: PERMISSION_CODES.GET_TREATMENTS,
    create: PERMISSION_CODES.CREATE_TREATMENT,
    update: PERMISSION_CODES.UPDATE_TREATMENT,
    delete: PERMISSION_CODES.DELETE_TREATMENT,
  },
  [PERMISSION_MODULES.PATIENT_TREATMENTS]: {
    view: PERMISSION_CODES.GET_PATIENT_TREATMENTS,
    create: PERMISSION_CODES.CREATE_PATIENT_TREATMENT,
    update: PERMISSION_CODES.UPDATE_PATIENT_TREATMENT,
  },
  [PERMISSION_MODULES.PAYMENTS]: {
    view: PERMISSION_CODES.GET_PAYMENTS,
    create: PERMISSION_CODES.CREATE_PAYMENT,
  },
  [PERMISSION_MODULES.CLINICAL_RECORDS]: {
    view: PERMISSION_CODES.GET_CLINICAL_RECORDS,
    create: PERMISSION_CODES.CREATE_CLINICAL_RECORD,
  },
} as const satisfies Record<TPermissionModule, TModuleCrudActions>;

export type TCrudModule = keyof typeof MODULE_CRUD;
